export enum Role {
  STUDENT = 'STUDENT',
  ACADEMIC = 'ACADEMIC',
  HEAD_STUDY_PROGRAM = 'HEAD_STUDY_PROGRAM',
  HEAD_DEPARTEMENT = 'HEAD_DEPARTEMENT',
  SUPERVISOR = 'SUPERVISOR',
  LECTURER = 'LECTURER',
  ADMIN = 'ADMIN',
}

export type RoleType = {
  roles: Role[];
};
